name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v1.1
        if: runner.os == 'Windows'
      - run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF
      - run: cmake --build build --config Release --parallel
      - uses: actions/upload-artifact@v4
        with:
          name: iso-kernos-${{ matrix.os }}
          path: build/**/iso-kernos*
